### ISSUE TITLE
English version

### ISSUE THREAD

**Issue by basher83** [Danilop95/Proxmox-local#1]
I really like this script. Is there any chance you could do an English translation/version of it as well?

**Comment by Danilop95** [comment]
Hello, excuse my English, it's not very good. I'm trying to create the English version, I'll release it as soon as possible.

**Comment by Danilop95** [comment]
@basher83 I have already uploaded the update. I have added a language menu. Let me know what you think. Thank you.

**Comment by basher83** [comment]
@Danilop95 This is perfect! Thank you so much!

**Comment by Danilop95** [comment]
perfect work
